"""Generate legacy_roster/schema_names.py from the game's own database schema.

    python tools/decode_schema.py "<NHL Legacy Edition.iso>"      (or an extracted game folder)

The disc holds db/nhlng-meta.xml inside cacheboot.big. It lists every table and field of the
game database with both its scrambled 4-character tag (what a roster save stores) and its real
name. Only the tables that are part of a roster save are written out.
"""
import os
import sys
import xml.etree.ElementTree as ET

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from isotools import EbArchive  # noqa: E402

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'legacy_roster', 'schema_names.py')


def main(source):
    xml = EbArchive.open(source, 'cacheboot.big').read('db/nhlng-meta.xml').decode('utf-8-sig')
    root = ET.fromstring(xml)
    tables, fields = {}, {}
    for t in root.iter('table'):
        if 'rosters' not in (t.get('savegroups') or '').split(','):
            continue
        tag = t.get('shortname')
        tables[tag] = t.get('name')
        fields[tag] = {f.get('shortname'): f.get('name') for f in t.iter('field')}
    lines = ['"""Real names of the tables and fields found in a roster save.',
             '',
             'Generated by tools/decode_schema.py from db/nhlng-meta.xml on the game disc -- do not edit.',
             'TABLES maps a table tag to its name; FIELDS maps tag -> {field tag: field name}.',
             '"""',
             '',
             'TABLES = {']
    for tag in sorted(tables, key=lambda k: tables[k]):
        lines.append(f"    {tag!r}: {tables[tag]!r},")
    lines += ['}', '', 'FIELDS = {']
    for tag in sorted(fields, key=lambda k: tables[k]):
        lines.append(f"    {tag!r}: {{  # {tables[tag]}")
        row = '       '
        for ftag, fname in sorted(fields[tag].items(), key=lambda kv: kv[1]):
            item = f" {ftag!r}: {fname!r},"
            if len(row) + len(item) > 116:
                lines.append(row)
                row = '       '
            row += item
        lines.append(row)
        lines.append('    },')
    lines += ['}', '']
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))
    print(f"{len(tables)} tables, {sum(len(v) for v in fields.values())} fields -> {OUT}")


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
